"""
River Mask Generation Script

This script processes river shapefiles for a region of interest (ROI) through these steps:
1. Takes a rivers shapefile and crops it to the region of interest (ROI)
2. Dilates the rivers by a specified distance (default 180m)
3. Rasterizes the rivers and saves them to a GeoTIFF

The script uses a reference raster for the image target area generated by 1-rasterize_roi_shapes.py
to ensure consistent spatial properties.

Usage:
    Modify the parameters at the top of the script (roi_name, out_res, buffer_dist)
    and run the script.
"""

# %% 1.0 Libraries and directories
import os
import pprint as pp
import numpy as np
import geopandas as gpd

import rasterio as rio
from rasterio import features


roi_name = 'YKD_sub8'  # Name of the region of interest
out_res = 30 # ensure this matches the resolution of your analysis (e.g. 30m or 60m)
buffer_dist = 180 # The distance in meters to dilate/buffer the rivers

# These regions (MRD, TUK, AND) have the same river file
roi_prefix = roi_name.split('_')[0]
if roi_prefix in ['AND', 'TUK', 'MRD']:
    rivers_prefix = 'MRD'
else:
    rivers_prefix = roi_prefix

rivers_dir = f'./data/river_files/{rivers_prefix}_river.shp'
roi_dir = f'./data/roi_shapes/rois/{roi_prefix}_sub_rois.shp'
out_dir = f'./data/river_files/'
out_path = f'{out_dir}/{roi_name}_binary_rivers_dilated{buffer_dist}_res{out_res}.tif'

rivers = gpd.read_file(rivers_dir)
if rivers.crs is None:
    rivers.set_crs('EPSG:4326', inplace=True)
    print('Rivers were missing crs')
else:
    print(rivers.crs)


sub_rois = gpd.read_file(roi_dir)
roi = sub_rois[sub_rois['sub_name'] == roi_name]

# %% 2.0 Functions

def clip_dilate_rivers(
    rivers: gpd.GeoDataFrame, 
    roi: gpd.GeoDataFrame, 
    buffer_dist: int
):
    """
    Process river geometries by reprojecting, clipping to ROI, and dilating.
    
    Args:
        rivers (gpd.GeoDataFrame): GeoDataFrame containing river geometries
        roi (gpd.GeoDataFrame): GeoDataFrame containing ROI geometry
        buffer_dist (int): Distance in meters to dilate/buffer the rivers
    
    Returns:
        gpd.GeoSeries: Dilated river geometries in the ROI's UTM projection
        
    Process:
        1. Reprojects both rivers and ROI to the ROI's local UTM zone
        2. Clips the rivers to the ROI extent
        3. Dilates river geometries by the specified buffer distance
    """
    # Conversion to ROI's local UTM zone
    est_utm = rivers.estimate_utm_crs()
    est_utm_roi = roi.estimate_utm_crs()
    roi_utm = roi.to_crs(est_utm_roi)
    rivers_utm = rivers.to_crs(est_utm_roi)
    # Clip the rivers to roi and buffer thier shapes
    clipped_rivers = gpd.clip(rivers_utm, roi_utm)
    dilated_rivers = clipped_rivers.buffer(buffer_dist)
    # Bounds for the ROI to use in writing rivers raster
    roi_bounds = roi_utm.geometry.total_bounds

    return dilated_rivers

def make_river_mask(
    rivers_dilated: gpd.GeoDataFrame, 
    roi_mask_fp: str,
    out_path: str,
):
    """
    Create a binary raster mask from dilated river geometries.
    
    Args:
        rivers_dilated (gpd.GeoDataFrame): Dilated river geometries
        roi_mask_fp (str): File path to the reference ROI raster
        out_path (str): Output file path for the river mask
    
    Process:
        1. Uses the reference ROI raster to obtain spatial metadata
        2. Rasterizes the dilated river geometries with 1s for rivers, 0s elsewhere
        3. Writes the binary mask to the specified output path
    """

    with rio.open(roi_mask_fp) as ref:
        meta = ref.meta.copy()

    mask = features.rasterize(
        shapes=rivers_dilated.geometry,
        out_shape=(ref.height, ref.width),
        transform=ref.transform,
        fill=0,
        default_value=1,
        dtype='uint8'
    )

    with rio.open(out_path, 'w', **meta) as dst:
        dst.write(mask, indexes=1)

    print(f'Processed {out_path}')

# %% 3.0 Run the functions

rivers_dilated = clip_dilate_rivers(rivers, roi, buffer_dist)
roi_mask_fp = f'./data/roi_shapes/rois/rasterized_{roi_name}_shape_res{out_res}.tif'
make_river_mask(rivers_dilated, roi_mask_fp, out_path)


# %%
